### ISSUE TITLE
Update Team Page

### ISSUE THREAD

**Issue by skunichetty** [MichiganDataScienceTeam/website-redesign#55]
We will want to update the team page with information about new committees. I'll send all the details on Slack, but there are two components to this task + one stretch goal:

- [x] Add headshots and social links for all the new committee members (see the details sent on slack)
- [x] Update the committee member titles (see the details sent on slack)
- [x] **(Stretch)** Re-design the page layout so each committee has a carousel of member profiles. We have bigger committees now, so the mobile layout will not be as user-friendly if we just keep adding profiles to the page. Right now the profiles are just laid out vertically on mobile based on flex. A carousel might be easier to user. Feel free to disagree here though.

Tag: @Jmshaver and @andrewye16 (just to keep you in the loop)

@Jmshaver Let me know if you'd rather me take care of this, updating the page data is fairly straightforward; not sure I have the bandwidth to take a stab at the carousel though.

**Comment by Jmshaver** [comment]
I added the new headshots, updated people's information and changed the design so it is more condensed on mobile. Can one of you review the changes before I merge.

**Comment by skunichetty** [comment]
Love the new mobile layout actually, think that works much better than a carousel. Two things:
-  For the Finance Committee description, lets use the following - `The financial backbone of MDST, planning and allocating our monetary resources. Led by the VP of Finance.`
- I think for the project committee, we're missing Aaron?

Otherwise looks good to me. Tagging @andrewye16 in case he'd like to take a second look here.

**Comment by Jmshaver** [comment]
@skunichetty I updated the two things and I'll merge later today if there are no more comments

**Comment by skunichetty** [comment]
Looks good to me! Feel free to merge it.
